version: '3.8'

services:
  laundry-scheduler:
    image: ghcr.io/${GITHUB_REPOSITORY:-captainsloths/laundry-scheduler}:v1
    container_name: laundry-scheduler
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - TZ=UTC
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
